# Generated by Django 5.2.1 on 2025-05-28 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Фамилия и имя')),
                ('course', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Курс')),
                ('program', models.CharField(max_length=100, verbose_name='Программа')),
            ],
        ),
    ]
